name: Deploy to Synology NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          docker-compose -p catalogoeepsa up -d --build frontend backend db
