name: Deploy to Synology NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          # 1. Obtener el nombre del proyecto exacto de Synology
          PROJECT_NAME=$(docker inspect -f '{{ index .Config.Labels "com.docker.compose.project" }}' eepsa-db)
          echo "Deploying to project: $PROJECT_NAME"
          
          # 2. Descubrir la ruta absoluta real del Synology (ej. /volume1/docker/CatalogoEepsa)
          RUNNER_MOUNT=$(docker inspect -f '{{ range .Mounts }}{{ if eq .Destination "/opt/actions-runner/_work/CatalogoEepsa/CatalogoEepsa" }}{{ .Source }}{{ end }}{{ end }}' eepsa-github-runner)
          HOST_DIR=$RUNNER_MOUNT
          echo "Host project dir: $HOST_DIR"
          
          # 3. Forzar a docker-compose a usar la ruta absoluta del host para los volúmenes
          export HOST_PATH=$HOST_DIR
          
          docker-compose -p $PROJECT_NAME up -d --build frontend backend
          
          # 4. Copiar las imágenes a través de Docker hacia el volumen del host
          docker cp assets/img/. eepsa-backend:/app/public/img/
          
          # Ejecutar actualizacion de rutas de imagenes
          docker exec -i eepsa-db psql -U eepsa_user -d eepsa_catalog < db/update_prod.sql || true
